/*
 * This file is generated by jOOQ.
 */
package fyi.sorenneedscoffee.statistics.db;


import fyi.sorenneedscoffee.statistics.db.tables.Statistics;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in s13_statistics
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>s13_statistics.statistics</code>.
     */
    public static final Statistics STATISTICS = Statistics.STATISTICS;
}
