/*
 * This file is generated by jOOQ.
 */
package fyi.sorenneedscoffee.squier.db;


import fyi.sorenneedscoffee.squier.db.tables.Statistics;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>s13_statistics</code> 
 * schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index STATISTICS_PRIMARY = Indexes0.STATISTICS_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index STATISTICS_PRIMARY = Internal.createIndex("PRIMARY", Statistics.STATISTICS, new OrderField[] { Statistics.STATISTICS.DATE }, true);
    }
}
