/*
 * This file is generated by jOOQ.
 */
package fyi.sorenneedscoffee.squier.db;


import fyi.sorenneedscoffee.squier.db.tables.Statistics;
import fyi.sorenneedscoffee.squier.db.tables.records.StatisticsRecord;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships and constraints of tables of
 * the <code>s13_statistics</code> schema.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<StatisticsRecord> KEY_STATISTICS_PRIMARY = UniqueKeys0.KEY_STATISTICS_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<StatisticsRecord> KEY_STATISTICS_PRIMARY = Internal.createUniqueKey(Statistics.STATISTICS, "KEY_statistics_PRIMARY", Statistics.STATISTICS.DATE);
    }
}
