/*
 * This file is generated by jOOQ.
 */
package fyi.sorenneedscoffee.squier.db;


import fyi.sorenneedscoffee.squier.db.tables.Statistics;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.4"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class S13Statistics extends SchemaImpl {

    /**
     * The reference instance of <code>s13_statistics</code>
     */
    public static final S13Statistics S13_STATISTICS = new S13Statistics();
    private static final long serialVersionUID = -922181084;
    /**
     * The table <code>s13_statistics.statistics</code>.
     */
    public final Statistics STATISTICS = fyi.sorenneedscoffee.squier.db.tables.Statistics.STATISTICS;

    /**
     * No further instances allowed
     */
    private S13Statistics() {
        super("s13_statistics", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
                Statistics.STATISTICS);
    }
}
