/*
 * This file is generated by jOOQ.
 */
package fyi.sorenneedscoffee.xputil.db;


import fyi.sorenneedscoffee.xputil.db.tables.Users;


/**
 * Convenience access to all tables in s13_users
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>s13_users.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
